//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flip_Chess.Strings {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UI() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Flip_Chess.Strings.UI", typeof(UI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 About... 的本地化字符串。
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click 的本地化字符串。
        /// </summary>
        internal static string Click {
            get {
                return ResourceManager.GetString("Click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Computer 的本地化字符串。
        /// </summary>
        internal static string Computer {
            get {
                return ResourceManager.GetString("Computer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ysdy44@outlook.com 的本地化字符串。
        /// </summary>
        internal static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 mailto:ysdy44@outlook.com 的本地化字符串。
        /// </summary>
        internal static string FeedbackLink {
            get {
                return ResourceManager.GetString("FeedbackLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Feedback 的本地化字符串。
        /// </summary>
        internal static string FeedbackTitle {
            get {
                return ResourceManager.GetString("FeedbackTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Flip-Chess-UWP 的本地化字符串。
        /// </summary>
        internal static string Github {
            get {
                return ResourceManager.GetString("Github", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://github.com/ysdy44/Flip-Chess-UWP 的本地化字符串。
        /// </summary>
        internal static string GithubLink {
            get {
                return ResourceManager.GetString("GithubLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Github 的本地化字符串。
        /// </summary>
        internal static string GithubTitle {
            get {
                return ResourceManager.GetString("GithubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 When the game starts, click on the blank pieces 的本地化字符串。
        /// </summary>
        internal static string Guider001 {
            get {
                return ResourceManager.GetString("Guider001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Turn it into a red pawn or a black pawn 的本地化字符串。
        /// </summary>
        internal static string Guider002 {
            get {
                return ResourceManager.GetString("Guider002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Each pawn has its own level 的本地化字符串。
        /// </summary>
        internal static string Guider003 {
            get {
                return ResourceManager.GetString("Guider003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 7 &gt; 6 &gt; 5 &gt; 4 &gt; 3 &gt; 2 &gt; 1 的本地化字符串。
        /// </summary>
        internal static string Guider004 {
            get {
                return ResourceManager.GetString("Guider004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Generally, higher level pieces can eat adjacent pieces 的本地化字符串。
        /// </summary>
        internal static string Guider005 {
            get {
                return ResourceManager.GetString("Guider005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 7 &gt; 6 ，7 &gt; 5 的本地化字符串。
        /// </summary>
        internal static string Guider006 {
            get {
                return ResourceManager.GetString("Guider006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 However, only a level 1 piece can eat a level 7 pawn 的本地化字符串。
        /// </summary>
        internal static string Guider007 {
            get {
                return ResourceManager.GetString("Guider007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1 &gt; 7 的本地化字符串。
        /// </summary>
        internal static string Guider008 {
            get {
                return ResourceManager.GetString("Guider008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lose 的本地化字符串。
        /// </summary>
        internal static string Lose {
            get {
                return ResourceManager.GetString("Lose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Flip Chess 的本地化字符串。
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Next Step 的本地化字符串。
        /// </summary>
        internal static string NextStep {
            get {
                return ResourceManager.GetString("NextStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pause 的本地化字符串。
        /// </summary>
        internal static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pause Game 的本地化字符串。
        /// </summary>
        internal static string PauseGame {
            get {
                return ResourceManager.GetString("PauseGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Players 的本地化字符串。
        /// </summary>
        internal static string Players {
            get {
                return ResourceManager.GetString("Players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 to jump to the next level 的本地化字符串。
        /// </summary>
        internal static string ToNext {
            get {
                return ResourceManager.GetString("ToNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 to continue 的本地化字符串。
        /// </summary>
        internal static string ToPlay {
            get {
                return ResourceManager.GetString("ToPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 to come back 的本地化字符串。
        /// </summary>
        internal static string ToRestart {
            get {
                return ResourceManager.GetString("ToRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tutorial 的本地化字符串。
        /// </summary>
        internal static string Tutorial {
            get {
                return ResourceManager.GetString("Tutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1.0.0 的本地化字符串。
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Version 的本地化字符串。
        /// </summary>
        internal static string VersionTitle {
            get {
                return ResourceManager.GetString("VersionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Win 的本地化字符串。
        /// </summary>
        internal static string Win {
            get {
                return ResourceManager.GetString("Win", resourceCulture);
            }
        }
    }
}
